spring.application.name=product_management

# URI de los controllers
server.servlet.context-path=/api/v1

# Configuración de la base de datos
spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=exercise1
spring.datasource.password=exercise1

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Configuración de H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console